name: final_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  local_auth: ^2.3.0
  local_auth_android: ^1.0.36
  flutter_secure_storage: ^9.0.0
  supabase_flutter: ^2.6.0
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.0
  fl_chart: ^0.70.0
  table_calendar: ^3.1.2
  flutter_local_notifications: ^17.0.0
  easy_date_timeline: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true